[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
